### ISSUE TITLE
can this be integrate with kibana?

### ISSUE THREAD

**Issue by xycloud** [appbaseio/es-queryComposer#37]
can this be integrate with kibana5?

**Comment by siddharthlatest** [comment]
@xycloud Mirage can't be used as a plugin in Kibana 5 if that's what you are asking. Our recommended set up is to use this docker image if you are looking to run this on your server - https://hub.docker.com/r/appbaseio/mirage/.

Other options to run Mirage are the [hosted app](https://opensource.appbase.io/mirage/) and the [chrome extension](https://chrome.google.com/webstore/detail/mirage/dcnlpfmnpoggchflmdnkgiepijgljoka).
