### ISSUE TITLE
Run Query button positioning

### ISSUE THREAD

**Issue by metagrover** [appbaseio/es-queryComposer#39]
Run Query button gets dislocated when the query block's height reaches its position.

![screen shot 2017-05-10 at 7 41 07 pm](https://cloud.githubusercontent.com/assets/9116042/25903082/0dfec452-35b9-11e7-89d1-30d1fbdcfe1e.png)

**Comment by farhan687** [comment]
Fixed here d9f4643b27fa7ba732363b397800c3f195817c67
