### ISSUE TITLE
Elastic 1.7.3 Without HTTPS Basic Auth

### ISSUE THREAD

**Issue by rahst12** [appbaseio/es-queryComposer#40]
Hi,
   I'm running Elastic 1.7.3 without HTTPS Basic Auth.  I've installed the Mirage Docker version.  I can't seem to get it to connect.. Looking at the web debug console logs, it looks like it's not liking that I don't have a username/pass on the elastic url.

   Any advice would be great.. 

Thanks

**Comment by siddharthlatest** [comment]
@rahst12 Mirage is only compatible with v2.x and above.

**Comment by siddharthlatest** [comment]
We will look into the use of non-basic authenticated ES, cc @farhan687

**Comment by rahst12** [comment]
On the main page under the docker part it says: "Works with Elasticsearch versions **1.x**, 2.x and 5.x.".. Is that just out of date?

**Comment by rahst12** [comment]
I'm looking to upgrade elastic... Is there a plugin I should be looking for that does authentication?  I see references to Shield all over.

**Comment by siddharthlatest** [comment]
@rahst12 If you just need Basic Auth, it can be set up in a nginx conf. There are already docker images out there https://hub.docker.com/r/beevelop/nginx-basic-auth/ which can then forward to Elasticsearch. If you need something more sophisticated, you can then either go with Shield or 
https://github.com/floragunncom/search-guard.

**Comment by siddharthlatest** [comment]
**Conclusion:** 

1. Mirage isn't compatible with v1.x.
2. The docs have been updated at https://hub.docker.com/r/appbaseio/mirage/ with more details on how to setup CORS config with Elasticsearch.  
3. Mirage works with an Elasticsearch cluster both with and without a basic auth setup.
