### ISSUE TITLE
verbose stack Error: mirage@0.7.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch" `

### ISSUE THREAD

**Issue by svanschalkwyk** [appbaseio/es-queryComposer#41]
Have tried with node 8,7, etc. All versions have this problem. 
Funny thing, it used to work until last night.

0 info it worked if it ends with ok
1 verbose cli [ '/home/steph/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/home/steph/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mirage@0.7.0~prestart: mirage@0.7.0
6 silly lifecycle mirage@0.7.0~prestart: no script for prestart, continuing
7 info lifecycle mirage@0.7.0~start: mirage@0.7.0
8 verbose lifecycle mirage@0.7.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle mirage@0.7.0~start: PATH: /home/steph/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/steph/Apps/mirage/node_modules/.bin:/home/steph/.nvm/versions/node/v7.10.0/bin:/home/steph/bin:/home/steph/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/share/scala/bin:/home/steph/Apps/spark-2.1.1-bin-hadoop2.7/bin:/opt/TurboVNC/bin:/usr/local/share/scala/bin:/home/steph/Apps/spark-2.1.1-bin-hadoop2.7/bin:/opt/TurboVNC/bin:/usr/local/share/scala/bin:/home/steph/Apps/spark-2.1.1-bin-hadoop2.7/bin:/opt/TurboVNC/bin
10 verbose lifecycle mirage@0.7.0~start: CWD: /home/steph/Apps/mirage
11 silly lifecycle mirage@0.7.0~start: Args: [ '-c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch" ' ]
12 silly lifecycle mirage@0.7.0~start: Returned: code: 1  signal: null
13 info lifecycle mirage@0.7.0~start: Failed to exec start script
14 verbose stack Error: mirage@0.7.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/steph/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/steph/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mirage@0.7.0
16 verbose cwd /home/steph/Apps/mirage
17 error Linux 4.4.0-53-generic
18 error argv "/home/steph/.nvm/versions/node/v7.10.0/bin/node" "/home/steph/.nvm/versions/node/v7.10.0/bin/npm" "start"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error mirage@0.7.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch" `
23 error Exit status 1
24 error Failed at the mirage@0.7.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch" '.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the mirage package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc && concurrently "npm run tsc:w" "npm run lite" "gulp watch"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs mirage
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls mirage
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by svanschalkwyk** [comment]
Just started to work. Problem with node?

**Comment by siddharthlatest** [comment]
Hard to tell, closing this issue.
