### ISSUE TITLE
Authentication sign-in not working on chrome extension 

### ISSUE THREAD

**Issue by reedv** [appbaseio/es-queryComposer#43]
I was initially having trouble with the authentication for my local ES installation (with x-pack security) where every time I tried to sign in with the login window would continually reset. Looking at the chrome console, I saw that the username was being set to "localhost" with password "9200" the local ES port.
Pictured below:
 
![mirage_no-auth](https://user-images.githubusercontent.com/15711729/29594848-84ce6488-874f-11e7-8f4d-01c89585f8a6.png)

Looking at [this](https://github.com/appbaseio/mirage/issues/18) issue, I changed the config file to include:

>http.cors.allow-origin: "/.*/"
>http.cors.enabled: true
>http.cors.allow-headers : "X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization"
>http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
>http.cors.allow-credentials: true

and restarted elasticsearch and I am now this error, where the username and password is blank username="", password="":

![screenshot from 2017-08-22 15-27-58](https://user-images.githubusercontent.com/15711729/29594941-10705992-8750-11e7-9077-27277ac5ef72.png)

Are there any other things that I can try to fix this?

**Comment by siddharthlatest** [comment]
@reedv Does your index already exist?

**Comment by reedv** [comment]
yes

**Comment by siddharthlatest** [comment]
@reedv Can you try prefixing your cluster URL with http:// scheme? It should look like this:

![](https://i.imgur.com/dy8IMxK.png)

**Comment by reedv** [comment]
@siddharthlatest Using http:// scheme?localhost:9200 in the mirage cluster url field still gives a similar error:

![screenshot from 2017-08-22 15-52-48](https://user-images.githubusercontent.com/15711729/29595243-0108cb04-8752-11e7-8b1e-bdbde0d20952.png)

**Comment by siddharthlatest** [comment]
@reedv Your cluster URL should be `http://localhost:9200`.

**Comment by reedv** [comment]
@siddharthlatest Sorry, I didn't get what you meant then by prefixing scheme? in the cluster name. Using the url you recommended, I get:
![screenshot from 2017-08-22 15-58-38](https://user-images.githubusercontent.com/15711729/29595408-fabff6d6-8752-11e7-8a24-a357762d5b0e.png)
Using me credentials, the window just continually resets to blank fields.

**Comment by siddharthlatest** [comment]
@reedv Just seeing that you mentioned you are using X-Pack security. I haven't used it, but in this case, the cluster field should be filled like:

`http://username:password@localhost:9200`.

Let me know if this works.

**Comment by reedv** [comment]
A problem that I am seeing is that my password has the form "password@passwordContinued", so mirage is sending command  GET http://passwordContinued@localhost:9200/bank/_mapping/.

I will try changing the password and see what happens then.

**Comment by reedv** [comment]
@siddharthlatest changedd password to password123passwordContinued and am seeing this now:
![screenshot from 2017-08-22 16-12-49](https://user-images.githubusercontent.com/15711729/29595680-c5295858-8754-11e7-974f-b84f43bae1a4.png)
which seems to be working. Thanks for the advice and thanks for the quick response.

Trying to use the dejavu data view from mirage, I see this error in the console:
![screenshot from 2017-08-22 16-12-19](https://user-images.githubusercontent.com/15711729/29595711-f6e636ea-8754-11e7-8a9a-a154ee33de23.png)
Including it in this thread in case it is also related.

**Comment by siddharthlatest** [comment]
@reedv That's great to hear.

On the dejavu issue, I think it is requesting a http:// URL over an https:// connection. See your URL bar and enable loading unsafe scripts.

![](https://i.imgur.com/1imbDtt.png)

If you still see an issue with dejavu, the recommended place to file it would be https://github.com/appbaseio/dejavu/issues.

**Comment by reedv** [comment]
@siddharthlatest 
That worked, Thanks.
And yeah, I was going to post the issue to the dejavu issues, but figured it might be related since the behavior change was due to the mirage issue fix.
Anyway, you were super fast and super helpful, thanks again.
