### ISSUE TITLE
Couldn't connect to localhost elastic search service

### ISSUE THREAD

**Issue by yuseferi** [appbaseio/es-queryComposer#50]
I have elastic search service on my local on docker ( port is 9200 ) and I can access it via browser URL, but unfortunately, I can't connect to it via your plugin. ( I set URL to 127.0.0.1:9200 too, but not connected)

**Comment by iazel** [comment]
Just had this problem, the solution is to prepend `http://`, so in your case it would be:
```
http://127.0.0.1:9200
```

**Comment by siddharthlatest** [comment]
Sounds about right, a URL will need a http:// scheme prefix.
