### ISSUE TITLE
Fail to load demo data

### ISSUE THREAD

**Issue by leosuncin** [appbaseio/es-queryComposer#64]
I clicked on "Live demo with preloaded queries" but it never loads, checking the devtools shows an error when a remote request is made to https://scalr.api.appbase.io/App3/_mapping/ returns 500
```
{"status":500,"message":"Ops! There was a problem communicating with the server. Please try again later."}
```

**Comment by siddharthlatest** [comment]
@leosuncin Thanks for pointing this out, we need to update the app used for demo here.

**Comment by siddharthlatest** [comment]
This has been fixed.
